blog/urls.py
from django.conf.urls import url
from . import views


appname = 'blog'
urlpatterns = [
    url(r'^$', views.user_home, name='user_home'),
    url(r'^(?P<author_name>\w+)/(?P<blog_title>.+)/$', views.blog_detail, name='blog_detail'),
    url(r'^(?P<author_name>\w+)/write_blog$', views.write_blog, name='write_blog'),
    url(r'^(?P<author_name>\w+)/all$', views.recent_blog, name='recent_blog'),
]

mysite/urls.py
#URL namespaces allow you to uniquely reverse named URL patterns even if different applications use the same URL names.
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('account.urls', namespace='account', app_name='account')),
    url(r'^blog/', include('blog.urls', namespace='blog', app_name='blog')),
    url(r'^', include('blog.urls', namespace='blog', app_name='user_home')),
]

if settings.DEBUG:
       urlpatterns += static(settings.MEDIA_URL,
                             document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

from django.utils import timezone
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

    #objects = models.Manager() #the default manager
class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager,self).get_queryset().filter(status='published')

class Blog(models.Model):
    STATUS_CHOICES = (
        ('draft','Draft'), ('published','Published'),
    )
    title = models.CharField(max_length=250)
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)#Automatically set the field to now when the object is first created
    updated = models.DateTimeField(auto_now=True)#to be set up to now only automatically updated when calling Model.save().
    status = models.CharField(max_length=10,
                              choices=STATUS_CHOICES,
                              default='draft')
    author = models.ForeignKey(User, related_name='blog_blogs')
    published = PublishedManager()#our custom manager

    def __str__(self):
        return self.title

    #返回 URLc
    def get_absolute_url(self):
        return reverse('blog:blog_detail', kwargs = {'author_name':self.author.username,'blog_title':self.title})

    class Meta:
        unique_together = (("author", "title"),)
        ordering = ['-publish']

blog/views.py
from django.shortcuts import render,get_object_or_404
from .models import Blog
from django.http import HttpResponse,HttpRequest
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from .models import Blog
from django.shortcuts import redirect, render_to_response
from django.contrib.auth.models import User


def user_home(request):
    if request.user.is_authenticated:
        blog = request.user.blog_blogs.all()
        recent_blog = blog[0:5]
        return render(request, 'blog/post/home.html', {'user':request.user,'recent_blog':recent_blog})
    else:
        return redirect('account/login/')


def recent_blog(request, author_name):

    # add paginator
    object_list = request.user.blog_blogs.all()
    paginator = Paginator(object_list, 5)
    page = request.GET.get('page')
    try:
        blogs = paginator.page(page)
    except PageNotAnInteger:
        # if page is not an integer deliver the first page
        blogs = paginator.page(1)

    except EmptyPage:
        #if page is out of range deliver last page of results
        blogs = paginator.page(paginator.num_pages)

    return render(request, 'blog/post/allblog.html', {'page':page, 'recent_blog': blogs})


def blog_detail(request, author_name, blog_title):
    author = get_object_or_404(User, username=author_name)
    blogs = get_object_or_404(Blog, author=author, title=blog_title)

    if request.method == 'GET':
        return render(request,
                  'blog/post/article.html',
                  {'blog':blogs,}
                  )

def blog_share(request, blog_id):
    #retrieve blog by id
    blog = get_object_or_404(blog, id=blog_id, status='published')

    if request.method=='blog':
#Form was submitted
        form = EmailblogForm(request.blog)
        if form.is_valid():
            cd = form.cleaned_data
    else:
        form = EmailblogForm()

    return render(request,'blog/blog/share.html',{'blog':blog,'form':form})


def write_blog(request, author_name):
    if request.method == 'POST':
        blog_title = request.POST['blogtitle']
        blog_body = request.POST['blogbody']

        blog = Blog(
            title=blog_title,
            body=blog_body,
            author=request.user,
            status='published'
        )
        blog.save()
        return redirect('blog:user_home')
    else:
        return render(request, 'blog/post/writeblog.html',{'author_name':request.user.username})

blog/templates/blog/post/allblog.html
{% extends "blog/base.html" %}
{% load staticfiles %}
{% block head %}
    <link rel="stylesheet" href="{% static "blog/css/allblog.css" %}">
{% endblock %}
{% block title %}{% endblock %}
{% block content %}
    {% for blog in recent_blog %}
        <section class="article-preview">
        <a href="{{ blog.get_absolute_url }}">
            <div class="text-section">
                <div class="text-wrapper">
                    <p class="blog-title">{{ blog.title }}</p>
                    <p class="blog-body">{{  blog.body|slice:"200" }}</p>
                </div>
            </div>
        </a>
        </section>
    {% endfor %}
    {% include "blog/pagination.html" with page=recent_blog %}
{% endblock %}

blog/templates/blog/post/article.html
{% extends 'blog/base.html' %}
{% load staticfiles %}
{% block head %}
    <link rel="stylesheet" href="{% static "blog/css/article.css" %}">
{% endblock %}
{% block content %}
<div class="wrapper">
    <div class="blank"></div>
    <header>
        <p class="blog-title">{{ blog.title }}</p>
        <p class="blog-date">{{ blog.created }}</p>
    </header>
    <div class="blog-body">
        <p>{{ blog.body|linebreaksbr}}</p>
    </div>
    <div id="bottom">
    </div>
</div>
{% endblock %}

blog/templates/blog/post/home.html
{% extends 'blog/base.html' %}
{% load staticfiles %}
{% block head %}
    <link href="{% static "blog/css/home.css" %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <header>
        <div id="banner">
            <div id="inner">
                <div id="portrait"><img src="{{ user.profile.portrait.url }}"></div>
                <p class="subhead">{{ user.profile.intro }}</p>
            </div>
        </div>
    </header>

    <div class="content">
        {% for blog in recent_blog %}
            <section class="article-preview">
            <a href="{{ blog.get_absolute_url }}">
                <div class="text-section">
                    <div class="text-wrapper">
                        <p class="blog-title">{{ blog.title }}</p>
                        <p class="blog-body">{{ blog.body|slice:"200" }}</p>
                    </div>
                </div>
            </a>
            </section>
        {% endfor %}
        <div class="rest">
            <a href="{% url 'blog:recent_blog' author_name=user.username %}">查看全部</a>
        </div>
    </div>


    <div id="footer"><!--脚部-->
        <div class="copy">
            <p>&copy {{ user.username }} 2017</p>
        </div>
    </div>

{% endblock %}